# Generated by Django 4.2.16 on 2024-10-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinario', '0005_alter_mascota_raza_tipoespecie_alter_mascota_especie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoespecie',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la especie'),
        ),
    ]
