# Generated by Django 4.2.16 on 2024-10-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinario', '0007_cita_fecha_creacion_cita_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.IntegerField(choices=[(1, 'PENDIENTE'), (2, 'APROBADO'), (3, 'RECHAZADO')], default=1, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='cita',
            name='hora_cita',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de la cita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_cita',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de la cita'),
        ),
    ]
