# Generated by Django 4.2.16 on 2024-11-08 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinario', '0009_propietario_mascota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='propietario',
        ),
    ]
